/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalpoo;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class JFMCREDITO extends javax.swing.JFrame {

    /**
     * Creates new form JFMCREDITO
     */
    public JFMCREDITO() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JLBNOMBRECLIENTE = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JBTIPO = new javax.swing.JComboBox<>();
        JLBTARJETA = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTTABLE = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        JLBTOTAL = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        JTXNUMEROTARJETA = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        JBRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre Cliente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 117, 57));
        getContentPane().add(JLBNOMBRECLIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 330, 50));

        jLabel2.setText("Seleccione Tipo de Tarjeta :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 170, 30));

        JBTIPO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta de Debito", "Tarjeta de Credito" }));
        getContentPane().add(JBTIPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 280, 30));

        JLBTARJETA.setText("Numero de Tajeta de credito: ");
        getContentPane().add(JLBTARJETA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 170, 30));

        JTTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Tipo Tarjeta", "Numero", "Total a Pagar"
            }
        ));
        jScrollPane1.setViewportView(JTTABLE);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 520, 140));

        jLabel3.setText("Total a Pagar:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, 30));
        getContentPane().add(JLBTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 320, 40));

        jButton1.setText("Regresar ");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 120, 40));
        getContentPane().add(JTXNUMEROTARJETA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 280, 30));

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 120, 40));

        JBRegresar.setText("Regresar");
        JBRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(JBRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     String nombre=JLBNOMBRECLIENTE.getText();
     String total=JLBTOTAL.getText();
     String  tipo= JBTIPO.getSelectedItem().toString();
     String Numero=JTXNUMEROTARJETA.getText();
     Imprimir(nombre,total,tipo,Numero);
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JBRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRegresarActionPerformed
  dispose();
    }//GEN-LAST:event_JBRegresarActionPerformed

        private void Imprimir(String nombre,String total,String tipo,String numero){
    DefaultTableModel modelo=(DefaultTableModel) JTTABLE.getModel(); 
        //Sección 2
        Object [] fila=new Object[4]; 
        //Sección 3
        fila[0]=nombre; 
        fila[1]=total; 
        fila[2]=tipo; 
        fila[3]=numero; 
         //Sección 4
         modelo.addRow(fila); 
        //Sección 5
        JTTABLE.setModel(modelo); }
 
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBRegresar;
    private javax.swing.JComboBox<String> JBTIPO;
    public static javax.swing.JLabel JLBNOMBRECLIENTE;
    private javax.swing.JLabel JLBTARJETA;
    public static javax.swing.JLabel JLBTOTAL;
    private javax.swing.JTable JTTABLE;
    private javax.swing.JTextField JTXNUMEROTARJETA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
