/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalpoo;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class JFMEFECTIVO extends javax.swing.JFrame {
    /**
     * Creates new form JFMEFECTIVO
     */
    public JFMEFECTIVO() {
     
        initComponents();
         setLocationRelativeTo(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JLBPAGAR = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTXEFECTIVO = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JLBTOTAL = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JLBEFECTIVOCAJA = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JLBTOTALCAMBIODATO = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JLBDINEROINGRESADO = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JLBTOTALAVER = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JBDaCambio = new javax.swing.JButton();
        JBSALIR = new javax.swing.JButton();
        JBCALCULAR = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Total a Pagar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 131, 30));
        getContentPane().add(JLBPAGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 190, 30));

        jLabel3.setText("Efectivo Entregado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 110, 40));
        getContentPane().add(JTXEFECTIVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 190, 40));

        jLabel2.setText("Total de Cambio:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 120, 50));

        JLBTOTAL.setText("0");
        getContentPane().add(JLBTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 210, 40));

        jLabel4.setText("Total de Efectivo  Caja al Comienzo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 220, 40));

        JLBEFECTIVOCAJA.setText("0");
        getContentPane().add(JLBEFECTIVOCAJA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 180, 40));

        jLabel5.setText("Total de dato en Vuelto:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 150, 30));

        JLBTOTALCAMBIODATO.setText("0");
        getContentPane().add(JLBTOTALCAMBIODATO, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 190, 30));

        jLabel7.setText("Total de Dinero Ingresado: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 160, 40));

        JLBDINEROINGRESADO.setText("0");
        getContentPane().add(JLBDINEROINGRESADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 190, 40));

        jLabel8.setText("Total de A ver:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 130, 30));

        JLBTOTALAVER.setText("0");
        getContentPane().add(JLBTOTALAVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 190, 40));

        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuadracion de Caja"));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 480, 270));

        JBDaCambio.setText("Dar Cambio ");
        JBDaCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDaCambioActionPerformed(evt);
            }
        });
        getContentPane().add(JBDaCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 110, 30));

        JBSALIR.setText("Regresar");
        JBSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSALIRActionPerformed(evt);
            }
        });
        getContentPane().add(JBSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 110, 30));

        JBCALCULAR.setText("Cuadrar Caja");
        JBCALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCALCULARActionPerformed(evt);
            }
        });
        getContentPane().add(JBCALCULAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 30));

        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Total En Caja ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 102))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 510, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBDaCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDaCambioActionPerformed
calcularcambio();
JLBTOTALCAMBIODATO.setText(JLBTOTAL.getText());
JLBDINEROINGRESADO.setText(JTXEFECTIVO.getText());
    }//GEN-LAST:event_JBDaCambioActionPerformed

    private void JBSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSALIRActionPerformed
     dispose();
    Caja.Efectivocaja=JLBTOTALAVER.getText();
       JOptionPane.showMessageDialog(this, "Felicidades por su compra");
    }//GEN-LAST:event_JBSALIRActionPerformed

    private void JBCALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCALCULARActionPerformed
     calcularCaja();
    }//GEN-LAST:event_JBCALCULARActionPerformed

    private void calcularcambio(){
     String totalFac=JLBPAGAR.getText();
     String efectivoEntregrado=JTXEFECTIVO.getText();
     double total=0;
     DecimalFormat df = new DecimalFormat("#.00");
     totalFac=totalFac.replace(',', '.');
     double doutotalFac= Double.parseDouble(totalFac);
     double douefectivo = Double.parseDouble(efectivoEntregrado);
     total=douefectivo-doutotalFac;
     String totalString =String.valueOf( df .format(total));
     JLBTOTAL.setText(totalString);
    
    }
    private void calcularCaja(){
    DecimalFormat df = new DecimalFormat("#.00");
     double total=0;
     String inicioCaja=JLBEFECTIVOCAJA.getText();
     String Cambiodato=JLBTOTALCAMBIODATO.getText();
     String dineroingresado =JLBDINEROINGRESADO.getText();
     inicioCaja=inicioCaja.replace(',', '.');
     Cambiodato= Cambiodato.replace(',', '.');
     dineroingresado= dineroingresado.replace(',', '.');
     double iniciocajadou= Double.parseDouble( inicioCaja);
     double Caniodouble=Double.parseDouble(Cambiodato);
     double dineroingresadodouble=Double.parseDouble(dineroingresado);
     total=dineroingresadodouble+iniciocajadou;
     total=total-Caniodouble;
     String totalString=String.valueOf(total);
     JLBTOTALAVER.setText(totalString);
     
     
    }
        
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCALCULAR;
    private javax.swing.JButton JBDaCambio;
    private javax.swing.JButton JBSALIR;
    private javax.swing.JLabel JLBDINEROINGRESADO;
    public static javax.swing.JLabel JLBEFECTIVOCAJA;
    public static javax.swing.JLabel JLBPAGAR;
    private javax.swing.JLabel JLBTOTAL;
    private javax.swing.JLabel JLBTOTALAVER;
    private javax.swing.JLabel JLBTOTALCAMBIODATO;
    private javax.swing.JTextField JTXEFECTIVO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
